### ISSUE TITLE
[PE-D][Tester C] UI image text is quite small

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-1/tp#160]
The UI image in the UG is of a large window, while the text within is quite small. As a result, its text cannot really be read since the font size is relatively small. This may also depend on the window size/scaling or screen resolution used to view the docs.

![image.png](https://raw.githubusercontent.com/Cloud7050/ped/main/files/40a543b1-b0dd-41d6-8f18-7836a0348187.png)

This may apply to other screenshots in the UG as well, e.g.:

![image.png](https://raw.githubusercontent.com/Cloud7050/ped/main/files/25b60f4e-9b5e-495f-9b6e-ec3f1f2eda83.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Cloud7050/ped#1

**Comment by miljyy** [comment]
Possible solutions:
- Take screenshot from smaller window size 
- Crop existing screenshots
