### ISSUE TITLE
[PE-D][Tester E] AddRemark Command for invalid EID

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-1/tp#167]
Appears to be the wrong error output as it outputs 

```
Invalid command format! 
addremark: Adds a remark for an employee to the employee book. Parameters: id/EMPLOYEE ID r/REMARK
Example: addremark id/EID1234-5678 r/Good worker
```
 rather than the user does not exist in the address book

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: GSgiansen/ped#3

**Comment by inezkok** [comment]
Same for these commands:
- addremark
- deleteremark
- deleteleave
- editleave
- overtime
