### ISSUE TITLE
[PE-D][Tester E] Find by phone number

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-1/tp#174]
When generating the user, the phone number is not given with the +65 prefix, but when I wish to find the user by a phone number i have to follow the +65 prefix which might not be intuitive to users. This is when I use this command
find p/+65 81239876, but find p/81239876 does not produce any result

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: GSgiansen/ped#6

**Comment by s0ngyang** [comment]
Find command doesnt use prefixes, hence the command searches for "p/+65" "81239876" which still gives the correct result, while "p/81239876" doesn't show any results as there is no matching phone number
