### ISSUE TITLE
[PE-D][Tester D] Edit Command returns wrong priority or error messages.

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-1/tp#177]
The edit command prioritizes the error message for a wrong format of input given for a particular field over the error message for an invalid index given which may be incorrect.

Steps to reproduce:

Input an edit command with both an invalid index and any invalid field

Input: edit 10 e/as@a

![image.png](https://raw.githubusercontent.com/Fallman2/ped/main/files/fa384e6e-9453-42fb-8e3f-531b8bbf19ec.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Fallman2/ped#3

**Comment by s0ngyang** [comment]
This is because parse errors are raised before command errors. Given an input, we first parse it to ensure that it is valid. If it is valid, then the command is executed. If there are errors during execution, such as id does not exist, then command error will be raised.
