### ISSUE TITLE
[PE-D][Tester C] Leave list wording may not be grammatical

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-1/tp#184]
When a leave period is displayed in the output window, the header for the list reads "Leaves taken". It may be possible to enhance the wording for the way the word "leave" is being used. A header such as "On leave on:" may read in a more appealing way.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: Cloud7050/ped#8

**Comment by inezkok** [comment]
wrong wording used in message (functionality bug)

**Comment by miljyy** [comment]
Merely an enhancement to the wording, not a bug to fix.
