### ISSUE TITLE
[PE-D][Tester E] F1 in Help bar

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-1/tp#189]
Help button comes with F1 which I am unsure of the functionality of it

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: GSgiansen/ped#9

**Comment by s0ngyang** [comment]
press f1 to access help

**Comment by miljyy** [comment]
Mention this keyboard shortcut in the UG for Windows users only!
