### ISSUE TITLE
[PE-D][Tester B] Addleave: able to add a outdated date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-1/tp#195]
- Users are allowed to add leave dates for a contact with dates that are already over, rather dates past the current date

![Screenshot 2023-11-03 at 4.55.42 PM.png](https://raw.githubusercontent.com/Angelyxx/ped/main/files/6849a562-ba20-44e6-97f0-303d2537bf05.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Angelyxx/ped#4

**Comment by s0ngyang** [comment]
can limit earliest date to first day of current year
